### ISSUE TITLE
regexp escaping

### ISSUE THREAD

**Issue by Morriar** [nitlang/nit#2463] opened 2017-05-25 22:04 UTC
Not sure if this is a bug or something I don't understand.

Let's use an easy regexp `^[a-z\-_]$`

First without escaping:

~~~nit
var re = "^[a-z-_]$".to_re # Regex Error: Invalid range end
~~~

Ok, let's try with some escaping:

~~~nit
var re = "^[a-z\\-_]$".to_re

assert "a".has(re)
assert "z".has(re)
assert "-".has(re) # Runtime Error: Assert failed. WHUT?
assert "_".has(re)
~~~

Ok, maybe the escaping was only one backslash?

~~~nit
var re = "^[a-z\-_]$".to_re # Regex Error: Invalid range end
~~~

But if I do:

~~~nit
var re = "^[a-z_-]$".to_re

assert "a".has(re)
assert "z".has(re)
assert "-".has(re)
assert "_".has(re)
~~~

Everything is fine...

What is the correct and expected behavior with this?

**Comment by jcbrinfo** [comment] 2017-05-26 15:29
You simply get caught by one of the subtle differences between POSIX syntaxes (supported by the `re` library, ERE variant by default) and Perl syntaxes:

1. `[a-z-_]` should give a syntax error because in all POSIX syntaxes, to include `-` in a character class, it must be last or the first character inside the brackets. Else, a character range is assumed. Note that the strings `"^[a-z-_]$"` and `"^[a-z\-_]$"` are equivalent in Nit.
2. In both POSIX BRE and POSIX ERE, `\` has no particular meaning inside character classes. So, `[a-z\-_]` means “allow any character between `a` and `z`, or between `\` and `_`”.
3. See 1.
4. As indicated above, `[a-z_-]` will work as you expect because `-` is escaped the way POSIX prescribe.

See also: [Regex::extended](http://nitlanguage.org/doc/nitc/class_core__re__Regex.html#core__re__Regex__extended.definition)

**Comment by jcbrinfo** [comment] 2017-05-26 15:40
Bonus tip: if you want to use a closing bracket inside a character class, you put it first. Example: `[]a-z]`

**Closed** 2017-06-20 13:35 UTC

**Comment by xymus** [comment] 2017-06-20 13:39
The previous answer is right, it is the expected behavior. Thanks for the exchange, this issue may come in handy to others!
