### ISSUE TITLE
markdown cannot block in a list

### ISSUE THREAD

**Issue by privat** [nitlang/nit#2262] opened 2016-08-15 14:17 UTC
Indented & fenced blocks seems recognized by nitmd (fences are consumed) but rendered as plain paragraph. This is not the same behavior that github and the official markdown.

See https://gist.github.com/privat/4311b70d95a0d43e920e033033f50cd2 for an example.

This cause the bad rendering of http://nitlanguage.org/windows.html , especially since the renderning do not match the preview on github.

Reported-by: @xymus

**Comment by Morriar** [comment] 2016-09-02 16:15
Fences are interpreted correctly:

~~~markdown
1. Item
        ~~~
	block
	~~~
~~~

Renders:

~~~html
<ol>
<li>Item<pre><code>block
</code></pre>
</li>
</ol>
~~~

Will investigate for the blocks

**Comment by Morriar** [comment] 2016-09-02 16:24
Well, this is tricky.

In fact markdown does recognize code blocks in lists:

~~~markdown
1. Item
        block
~~~

It all about indentation: 8 spaces (explanation below)

~~~html
<ol>
<li>Item<pre><code>block
</code></pre>
</li>
</ol>
~~~

Will see if this can be fixed without destroying the fragile ecosystem au the parser...

**Comment by Morriar** [comment] 2016-09-02 17:02
Stating some facts about the github markdown:

## Github

### Blocks

4 spaces, no blank line: **not rendered**

~~~md
1. Item
    block
~~~

~~~html
<ol>
<li>Item
block</li>
</ol>
~~~

8 spaces, no blank line: **not rendered**

~~~md
1. Item
        block
~~~

~~~html
<ol>
<li>Item
block</li>
</ol>
~~~

4 spaces, blank line: **not rendered**

~~~md
1. Item

    block
~~~

~~~html
<ol>
<li>
<p>Item</p>

<p>block</p>
</li>
</ol>
~~~

8 spaces, blank line: **rendered**

~~~md
1. Item

        block
~~~

~~~html
<ol>
<li>
<p>Item</p>

<pre><code>block
</code></pre>
</li>
</ol>
~~~

### Fences

4 spaces, no blank line: **not rendered**

~~~md
1. Item
    ~~~
    block
    ~~~
~~~

~~~html
<ol>
<li>Item
~~~block~~~</li>
</ol>
~~~

8 spaces, no blank line: **not rendered**

~~~md
1. Item
        ~~~
        block
        ~~~
~~~

~~~html
<ol>
<li>Item
block</li>
</ol>
~~~

4 spaces, blank line: **rendered**

~~~md
1. Item

    ~~~
    block
    ~~~
~~~

~~~html
<ol>
<li>
<p>Item</p>

<p>block</p>
</li>
</ol>
~~~

8 spaces, blank line: **badly rendered**

~~~md
1. Item

        ~~~
        block
        ~~~
~~~

~~~html
<ol>
<li>
<p>Item</p>

<pre><code>~~~
block
~~~
</code></pre>
</li>
</ol>
~~~

So only 2 configurations are possible for blocks in lists:

Block, 8 spaces with blank line:

~~~md
1. Item

        block
~~~

Fences, 4 spaces with blank line:

~~~md
1. Item

    ~~~
    block
    ~~~
~~~

**Comment by Morriar** [comment] 2016-09-02 17:16
Comparison with nitmd behavior:

## Nitmd

### Blocks

4 spaces, no blank line: **not rendered** (same than github)

~~~md
1. Item
    block
~~~

~~~html
<ol>
<li>Item
block</li>
</ol>
~~~

8 spaces, no blank line: **rendered** (better than github)

~~~md
1. Item
        block
~~~

~~~html
<ol>
<li>Item<pre><code>block
</code></pre>
</li>
</ol>
~~~

4 spaces, blank line: **not rendered** (same)

~~~md
1. Item

    block
~~~

~~~html
<ol>
<li>
<p>Item</p>

<p>block</p>
</li>
</ol>
~~~

8 spaces, blank line: **rendered** (same)

~~~md
1. Item

        block
~~~

~~~html
<ol>
<li>
<p>Item</p>

<pre><code>block
</code></pre>
</li>
</ol>
~~~

### Fences

4 spaces, no blank line: **rendered** (better than github)

~~~md
1. Item
    ~~~
    block
    ~~~
~~~

~~~html
<ol>
<li>Item<pre><code>block
</code></pre>
</li>
</ol>
~~~

8 spaces, no blank line: **rendered** (but fences are considered plain text within a codeblock, somehow this is what we can expect, still better than github)

~~~md
1. Item
        ~~~
        block
        ~~~
~~~

~~~html
<ol>
<li>Item<pre><code>~~~
block
~~~
</code></pre>
</li>
</ol>
~~~

4 spaces, blank line: **rendered** (same)

~~~md
1. Item

    ~~~
    block
    ~~~
~~~

~~~html
<ol>
<li>
<p>Item</p>

<p>block</p>
</li>
</ol>
~~~

8 spaces, blank line: **badly rendered** (same as github)

~~~md
1. Item

        ~~~
        block
        ~~~
~~~

~~~html
<ol>
<li>
<p>Item</p>

<pre><code>~~~
block~~~
</code></pre>
</li>
</ol>
~~~

**Comment by Morriar** [comment] 2016-09-02 17:19
## Final comparison

For github:
* Block, 8 spaces with blank line
* Fences, 4 spaces with blank line

For nitmd:
* Block, 8 spaces with no blank line
* Block, 8 spaces with blank line
* Fences, 4 spaces with no blank line
* Fences, 4 spaces with blank line

So nitmd offer the same behavior then github with something more: the blank line is not mandatory.

**Closed by Morriar** 2016-09-02 17:19 UTC
Labels: bug

**Comment by xymus** [comment] 2016-09-02 17:37
Did you close this a bit too fast? I feel that you did not address what did not work in @privat code sample.

I understand now that the problem is that nitmd doesn't support 3 space indentation + blocks/fences? It still looks like a bug to me, from what I understand it goes against the markdown syntax, plus both pandoc and github supports variable indentation. Also, the github text editor suggests a 3 space indentation on numbered list with the visible tab line.

Still adding a space to the indentation is a temporary workaround: https://github.com/nitlang/nitlanguage/commit/85401d77069ad5cbda46acf1b0953c3035cefd90

**Comment by xymus** [comment] 2016-09-02 17:45
Should I reopen this issue (the description was wide but the example still point to the bug) or open a new one?

**Comment by Morriar** [comment] 2016-09-02 17:45
As shown before, nit md follows the same behavior for list + block.

> Also, the github text editor suggests a 3 space indentation on numbered list with the visible tab line.

Not sure to understand, can you link me the reference?
